language: php

php:
  - 5.4

sudo: false

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

before_install:
  - printf "\n" |pecl install imagick
  - phpenv config-add .travis.php.ini
  - if [ -f ~/composer/composer.phar ]; then mv ~/composer/composer.phar ./; else wget https://getcomposer.org/composer.phar; fi
  - mkdir -p ~/composer
  - cp composer.phar ~/composer/composer.phar

install:
  - php -d memory_limit=-1 ./composer.phar install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: 091f85e6e1566ef155539cdd8cc3b8bf1f470f0a30db63435c9a731050ba8b2c 

after_script:
  - ./bin/test-reporter
