parameters:
    router.class : 'OpenOrchestra\FrontBundle\Routing\OpenOrchestraRouter'
    router.options.generator_class : 'OpenOrchestra\FrontBundle\Routing\OpenOrchestraUrlGenerator'
    router.options.generator_base_class : 'OpenOrchestra\FrontBundle\Routing\OpenOrchestraUrlGenerator'
    router.options.generator_dumper_class: OpenOrchestra\FrontBundle\Routing\Generator\Dumper\OpenOrchestraGeneratorDumper

    open_orchestra_front.database.route_loader.class: OpenOrchestra\FrontBundle\Routing\DatabaseRouteLoader
    open_orchestra_front.redirection.route_loader.class: OpenOrchestra\FrontBundle\Routing\RedirectionLoader

services:
    open_orchestra_front.redirection.route_loader:
        class: %open_orchestra_front.redirection.route_loader.class%
        arguments:
            - @open_orchestra_model.repository.redirection
            - @open_orchestra_model.repository.node
            - @open_orchestra_model.repository.site
        tags:
            - { name: routing.loader }
    open_orchestra_front.database.route_loader:
        class: %open_orchestra_front.database.route_loader.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @open_orchestra_model.repository.site
        tags:
            - { name: routing.loader }
