parameters:
    open_orchestra_front.manager.sitemap.class: OpenOrchestra\FrontBundle\Manager\SitemapManager
    open_orchestra_front.manager.robots.class: OpenOrchestra\FrontBundle\Manager\RobotsManager
    open_orchestra_front.manager.sub_query_parameters.class: OpenOrchestra\FrontBundle\Manager\SubQueryParametersManager

    open_orchestra_front.subscriber.check_routing_cache.class: OpenOrchestra\FrontBundle\EventSubscriber\CheckRoutingCacheViabilitySubscriber

services:
    open_orchestra_front.manager.sitemap:
        class: %open_orchestra_front.manager.sitemap.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @router
            - @serializer
            - @filesystem
    open_orchestra_front.manager.robots:
        class: %open_orchestra_front.manager.robots.class%
        arguments:
            - @filesystem

    open_orchestra_front.subscriber.check_routing_cache:
        class: %open_orchestra_front.subscriber.check_routing_cache.class%
        arguments:
            - @router
            - @open_orchestra_model.repository.node
        tags:
            - { name: kernel.event_subscriber }
    open_orchestra_front.manager.sub_query_parameters:
        class: %open_orchestra_front.manager.sub_query_parameters.class%
