parameters:
    open_orchestra_front.subscriber.kernel_exception.class: OpenOrchestra\FrontBundle\EventSubscriber\KernelExceptionSubscriber

services:
    open_orchestra_front.subscriber.kernel_exception:
        class: '%open_orchestra_front.subscriber.kernel_exception.class%'
        arguments:
            - '@open_orchestra_model.repository.site'
            - '@open_orchestra_model.repository.node'
            - '@templating'
            - '@request_stack'
            - '@open_orchestra_display.manager.context'
            - '@open_orchestra_front.manager.template'
        tags:
            - { name: kernel.event_subscriber }
