parameters:
    open_orchestra_front.twig.orchestra_twig_engine.class: OpenOrchestra\FrontBundle\Twig\OrchestraTwigEngine
    open_orchestra_front.extension.sub_query.class: OpenOrchestra\FrontBundle\Twig\SubQueryGeneratorExtension
    open_orchestra_front.extension.routing_node.class: OpenOrchestra\FrontBundle\Twig\RoutingNodeExtension
    open_orchestra_front.extension.render_area.class: OpenOrchestra\FrontBundle\Twig\RenderAreaExtension
    open_orchestra_front.extension.create_block.class: OpenOrchestra\FrontBundle\Twig\CreateBlockExtension
    open_orchestra_front.extension.get_special_page.class: OpenOrchestra\FrontBundle\Twig\GetSpecialPageExtension

services:
    open_orchestra_front.twig.orchestra_twig_engine:
        class: '%open_orchestra_front.twig.orchestra_twig_engine.class%'
        arguments:
            - '@twig'
            - '@templating.name_parser'
            - '@templating.locator'
            - '@request_stack'
            - '%open_orchestra_front.devices%'
            - '%open_orchestra_front.device_type_field%'
    open_orchestra_front.extension.sub_query:
        class: '%open_orchestra_front.extension.sub_query.class%'
        calls:
            - [ setContainer,[ '@service_container' ] ]
        tags:
            - { name: twig.extension }
    open_orchestra_front.extension.routing_node:
        class: '%open_orchestra_front.extension.routing_node.class%'
        arguments:
            - '@router'
            - '@open_orchestra_display.manager.site'
            - '@open_orchestra_model.repository.node'
        tags:
            - { name: twig.extension }
    open_orchestra_front.extension.render_area:
        class: '%open_orchestra_front.extension.render_area.class%'
        tags:
            - { name: twig.extension }
    open_orchestra_front.extension.create_block:
        class: '%open_orchestra_front.extension.create_block.class%'
        calls:
            - [ setContainer,[ '@service_container' ] ]
        tags:
            - { name: twig.extension }
    open_orchestra_front.extension.get_special_page:
        class: '%open_orchestra_front.extension.get_special_page.class%'
        arguments:
            - '@open_orchestra_model.repository.node'
            - '@open_orchestra_display.manager.site'
        tags:
            - { name: twig.extension }
